name: flutter_application
description: "A new Meter reading app."
publish_to: 'none'
version: 1.0.0+1

environment:
  # 💡 កែសម្រួល៖ បើកទំហំទាញយកឱ្យទូលាយ ដើម្បីគាំទ្របណ្ណាល័យ OCR និងទប់ស្កាត់កំហុស Dependency Conflict
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # បណ្ណាល័យស្នូលដែលស៊ីសង្វាក់គ្នាជាមួយ UI, Voice Logic និង ដាតាបេស រួចជាស្រេច
  sqflite: ^2.3.0
  path: ^1.8.3
  file_picker: ^8.0.0
  path_provider: ^2.1.1
  mobile_scanner: ^7.0.0
  speech_to_text: ^7.0.0
  image_picker: ^1.0.7
  image_cropper: ^8.0.2
  google_mlkit_commons: ^0.12.0
  google_mlkit_text_recognition: ^0.16.0
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  share_plus: ^12.0.2
  shared_preferences: ^2.0.15
  flutter_blue_plus: ^1.31.0
  excel: ^4.0.6
  geolocator: ^14.0.2
  gal: ^2.3.3
  http: ^1.6.0

  # Cloud Backup & Sync dependencies
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7
  firebase_storage: ^13.4.6
  google_sign_in: ^6.2.1
  googleapis: ^16.0.0
  googleapis_auth: ^2.3.3
  device_info_plus: ^9.1.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # 💡 កែសម្រួល៖ បន្ថែមផ្លូវរូបភាព logo.png ចូលមកវិញ ដើម្បីកុំឱ្យគាំង UI ត្រង់ AppDrawer
  assets:
    - assets/sn_meter.db
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/edcon.png"